include_guard(GLOBAL)

#
# add a set of global variables to get colored output in terminal messages
#
macro(cmake_add_termcolors)
  if(WIN32)
    set(CMAKE_COLOR_ESC          "")
    set(CMAKE_COLOR_RESET        "")
    set(CMAKE_COLOR_BOLD         "")
    set(CMAKE_COLOR_RED          "")
    set(CMAKE_COLOR_GREEN        "")
    set(CMAKE_COLOR_YELLOW       "")
    set(CMAKE_COLOR_BLUE         "")
    set(CMAKE_COLOR_MAGENTA      "")
    set(CMAKE_COLOR_CYAN         "")
    set(CMAKE_COLOR_WHITE        "")
    set(CMAKE_COLOR_BOLD_RED     "")
    set(CMAKE_COLOR_BOLD_GREEN   "")
    set(CMAKE_COLOR_BOLD_YELLOW  "")
    set(CMAKE_COLOR_BOLD_BLUE    "")
    set(CMAKE_COLOR_BOLD_MAGENTA "")
    set(CMAKE_COLOR_BOLD_CYAN    "")
    set(CMAKE_COLOR_BOLD_WHITE   "")
  else(WIN32)
    string(ASCII 27 CMAKE_COLOR_ESC)
    set(CMAKE_COLOR_RESET        "${CMAKE_COLOR_ESC}[m")
    set(CMAKE_COLOR_BOLD         "${CMAKE_COLOR_ESC}[1m")
    set(CMAKE_COLOR_RED          "${CMAKE_COLOR_ESC}[31m")
    set(CMAKE_COLOR_GREEN        "${CMAKE_COLOR_ESC}[32m")
    set(CMAKE_COLOR_YELLOW       "${CMAKE_COLOR_ESC}[33m")
    set(CMAKE_COLOR_BLUE         "${CMAKE_COLOR_ESC}[34m")
    set(CMAKE_COLOR_MAGENTA      "${CMAKE_COLOR_ESC}[35m")
    set(CMAKE_COLOR_CYAN         "${CMAKE_COLOR_ESC}[36m")
    set(CMAKE_COLOR_WHITE        "${CMAKE_COLOR_ESC}[37m")
    set(CMAKE_COLOR_BOLD_RED     "${CMAKE_COLOR_ESC}[1;31m")
    set(CMAKE_COLOR_BOLD_GREEN   "${CMAKE_COLOR_ESC}[1;32m")
    set(CMAKE_COLOR_BOLD_YELLOW  "${CMAKE_COLOR_ESC}[1;33m")
    set(CMAKE_COLOR_BOLD_BLUE    "${CMAKE_COLOR_ESC}[1;34m")
    set(CMAKE_COLOR_BOLD_MAGENTA "${CMAKE_COLOR_ESC}[1;35m")
    set(CMAKE_COLOR_BOLD_CYAN    "${CMAKE_COLOR_ESC}[1;36m")
    set(CMAKE_COLOR_BOLD_WHITE   "${CMAKE_COLOR_ESC}[1;37m")
  endif(WIN32)
endmacro(cmake_add_termcolors)